apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
  labels:
    app: grafana-svc
    component: core
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: grafana
    component: core