apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
  labels:
    app: prometheus-svc
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      protocol: TCP
      name: webui
  selector:
    app: prometheus
    component: core